### ISSUE TITLE
get_left_neighbor: attempt to subtract with overflow

### ISSUE THREAD

**Issue by ShampooDeng** [ShampooDeng/triangulate-rs-egui#12]
[2024-06-09T08:02:34Z DEBUG triangulate_rs::app] current cursor position:(173,557)
[2024-06-09T08:02:34Z DEBUG triangulate_rs::app] Pushing point coordinate:(173,15)
[2024-06-09T08:02:34Z DEBUG triangulate_rs::app] current cursor position:(173,556)
[2024-06-09T08:02:34Z DEBUG triangulate_rs::app] current cursor position:(173,556)
[2024-06-09T08:02:34Z DEBUG triangulate_rs::app] current cursor position:(173,555)
[2024-06-09T08:02:34Z DEBUG triangulate_rs::app] current cursor position:(173,551)
[2024-06-09T08:02:34Z DEBUG triangulate_rs::app] current cursor position:(286,480)
[2024-06-09T08:02:34Z DEBUG triangulate_rs::app] Pushing point coordinate:(286,92)
[2024-06-09T08:02:34Z DEBUG triangulate_rs::app] current cursor position:(286,480)
[2024-06-09T08:02:34Z DEBUG triangulate_rs::app] current cursor position:(286,480)
[2024-06-09T08:02:34Z DEBUG triangulate_rs::app] current cursor position:(287,480)
[2024-06-09T08:02:34Z DEBUG triangulate_rs::app] current cursor position:(287,480)
[2024-06-09T08:02:34Z DEBUG triangulate_rs::app] current cursor position:(288,480)
[2024-06-09T08:02:34Z DEBUG triangulate_rs::app] current cursor position:(290,482)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(409,569)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] Pushing point coordinate:(409,3)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(409,569)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(411,569)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(412,568)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(512,472)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] Pushing point coordinate:(512,100)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(512,472)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(512,472)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(513,472)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(513,472)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(513,472)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(521,474)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(677,568)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] Pushing point coordinate:(677,4)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(678,567)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(679,565)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(680,564)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] current cursor position:(637,349)
[2024-06-09T08:02:35Z DEBUG triangulate_rs::app] Pushing point coordinate:(637,223)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(636,349)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(636,349)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(636,349)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(635,349)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(570,261)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] Pushing point coordinate:(570,311)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(570,261)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(570,261)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(570,261)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(569,260)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(568,260)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(510,330)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] Pushing point coordinate:(510,242)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(510,330)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(510,330)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(509,330)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(509,330)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(505,332)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] current cursor position:(426,331)
[2024-06-09T08:02:36Z DEBUG triangulate_rs::app] Pushing point coordinate:(426,241)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] current cursor position:(387,231)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] Pushing point coordinate:(387,341)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] current cursor position:(387,229)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] current cursor position:(387,229)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] current cursor position:(387,229)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] current cursor position:(387,229)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] current cursor position:(226,210)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] Pushing point coordinate:(226,362)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] current cursor position:(225,210)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] current cursor position:(224,212)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] current cursor position:(224,213)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] current cursor position:(207,347)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] Pushing point coordinate:(207,225)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] current cursor position:(207,347)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] current cursor position:(206,348)
[2024-06-09T08:02:37Z DEBUG triangulate_rs::app] current cursor position:(206,349)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(124,409)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] Pushing point coordinate:(124,163)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(124,409)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(122,410)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(122,411)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(49,440)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] Pushing point coordinate:(49,132)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(48,440)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(47,440)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(46,440)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(45,441)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(44,441)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(81,308)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] Pushing point coordinate:(81,264)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(81,308)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(81,308)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(82,307)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(82,307)
[2024-06-09T08:02:38Z DEBUG triangulate_rs::app] current cursor position:(84,307)
[2024-06-09T08:02:39Z DEBUG triangulate_rs::app] current cursor position:(103,560)
[2024-06-09T08:02:39Z DEBUG triangulate_rs::app] Pushing point coordinate:(103,12)
[2024-06-09T08:02:39Z DEBUG triangulate_rs::app] current cursor position:(103,560)
[2024-06-09T08:02:39Z DEBUG triangulate_rs::app] current cursor position:(103,560)
[2024-06-09T08:02:39Z DEBUG triangulate_rs::app] current cursor position:(103,560)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(131,526)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] Pushing point coordinate:(131,46)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(131,526)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(131,526)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(131,525)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(131,525)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(132,524)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(133,522)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(236,462)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] Pushing point coordinate:(236,110)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(236,462)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(236,462)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(238,462)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(362,527)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] Pushing point coordinate:(362,45)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(363,527)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(364,527)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(523,411)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] Pushing point coordinate:(523,161)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(523,411)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(523,411)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(524,410)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(525,410)
[2024-06-09T08:02:42Z DEBUG triangulate_rs::app] current cursor position:(528,411)
[2024-06-09T08:02:43Z DEBUG triangulate_rs::app] current cursor position:(636,536)
[2024-06-09T08:02:43Z DEBUG triangulate_rs::app] Pushing point coordinate:(636,36)
[2024-06-09T08:02:43Z DEBUG triangulate_rs::app] current cursor position:(636,536)
[2024-06-09T08:02:43Z DEBUG triangulate_rs::app] current cursor position:(636,536)
[2024-06-09T08:02:43Z DEBUG triangulate_rs::app] current cursor position:(636,536)
[2024-06-09T08:02:43Z DEBUG triangulate_rs::app] current cursor position:(640,534)
[2024-06-09T08:02:43Z DEBUG triangulate_rs::app] current cursor position:(713,385)
[2024-06-09T08:02:43Z DEBUG triangulate_rs::app] Pushing point coordinate:(713,187)
[2024-06-09T08:02:43Z DEBUG triangulate_rs::app] current cursor position:(653,198)
[2024-06-09T08:02:43Z DEBUG triangulate_rs::app] Pushing point coordinate:(653,374)
[2024-06-09T08:02:43Z DEBUG triangulate_rs::app] current cursor position:(653,198)
[2024-06-09T08:02:43Z DEBUG triangulate_rs::app] current cursor position:(653,197)
[2024-06-09T08:02:43Z DEBUG triangulate_rs::app] current cursor position:(653,197)
[2024-06-09T08:02:43Z DEBUG triangulate_rs::app] current cursor position:(653,197)
[2024-06-09T08:02:43Z DEBUG triangulate_rs::app] current cursor position:(653,197)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(561,167)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] Pushing point coordinate:(561,405)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(560,167)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(559,168)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(558,169)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(492,272)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] Pushing point coordinate:(492,300)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(492,272)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(492,272)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(491,272)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(322,245)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] Pushing point coordinate:(322,327)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(322,245)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(322,244)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(321,242)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(291,192)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] Pushing point coordinate:(291,380)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(291,192)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(291,192)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(290,192)
[2024-06-09T08:02:44Z DEBUG triangulate_rs::app] current cursor position:(289,192)
[2024-06-09T08:02:45Z DEBUG triangulate_rs::app] current cursor position:(180,230)
[2024-06-09T08:02:45Z DEBUG triangulate_rs::app] Pushing point coordinate:(180,342)
[2024-06-09T08:02:45Z DEBUG triangulate_rs::app] current cursor position:(179,230)
[2024-06-09T08:02:45Z DEBUG triangulate_rs::app] current cursor position:(178,231)
[2024-06-09T08:02:45Z DEBUG triangulate_rs::app] current cursor position:(177,232)
[2024-06-09T08:02:45Z DEBUG triangulate_rs::app] current cursor position:(176,234)
[2024-06-09T08:02:45Z DEBUG triangulate_rs::app] current cursor position:(120,316)
[2024-06-09T08:02:45Z DEBUG triangulate_rs::app] Pushing point coordinate:(120,256)
[2024-06-09T08:02:45Z DEBUG triangulate_rs::app] current cursor position:(120,318)
[2024-06-09T08:02:45Z DEBUG triangulate_rs::app] current cursor position:(118,321)
[2024-06-09T08:02:45Z DEBUG triangulate_rs::app] current cursor position:(65,401)
[2024-06-09T08:02:45Z DEBUG triangulate_rs::app] Pushing point coordinate:(65,171)
[2024-06-09T08:02:46Z DEBUG triangulate_rs::app] current cursor position:(293,392)
[2024-06-09T08:02:46Z DEBUG triangulate_rs::app] Pushing point coordinate:(293,180)
[2024-06-09T08:02:46Z DEBUG triangulate_rs::app] current cursor position:(293,392)
[2024-06-09T08:02:46Z DEBUG triangulate_rs::app] current cursor position:(293,392)
[2024-06-09T08:02:46Z DEBUG triangulate_rs::app] current cursor position:(295,392)
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] vertex7 is start vertex
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] vertex10 is start vertex
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] vertex6 is regular vertex
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] interior is left to vertex6
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] vertex11 is regular vertex
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] interior is right to vertex11
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] vertex9 is regular vertex
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] interior is left to vertex9
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] vertex8 is merge vertex
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] vertex12 is regular vertex
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] interior is right to vertex12
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] vertex5 is regular vertex
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] interior is left to vertex5
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] vertex14 is split vertex
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] vertex13 is end vertex
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] vertex3 is split vertex
[2024-06-09T08:02:48Z DEBUG triangulate_rs::triangulate_2] vertex1 is split vertex
thread 'main' panicked at src\triangulate_2.rs:273:19:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\triangulate_rs.exe` (exit code: 101)

 *  The terminal process "C:\Users\Liu\.cargo\bin\cargo.exe 'run'" terminated with exit code: 101. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by ShampooDeng** [comment]
[2024-06-15T14:42:46Z DEBUG triangulate_rs::app] current cursor position:(98,517)
[2024-06-15T14:42:46Z DEBUG triangulate_rs::app] Pushing point coordinate:(98,55)
[2024-06-15T14:42:46Z DEBUG triangulate_rs::app] current cursor position:(98,517)
[2024-06-15T14:42:46Z DEBUG triangulate_rs::app] current cursor position:(98,517)
[2024-06-15T14:42:46Z DEBUG triangulate_rs::app] current cursor position:(97,517)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] current cursor position:(215,423)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] Pushing point coordinate:(215,149)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] current cursor position:(216,423)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] current cursor position:(217,423)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] current cursor position:(219,426)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] current cursor position:(408,532)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] Pushing point coordinate:(408,40)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] current cursor position:(408,532)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] current cursor position:(408,532)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] current cursor position:(408,532)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] current cursor position:(409,529)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] current cursor position:(480,332)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] Pushing point coordinate:(480,240)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] current cursor position:(480,332)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] current cursor position:(480,331)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] current cursor position:(481,332)
[2024-06-15T14:42:47Z DEBUG triangulate_rs::app] current cursor position:(484,337)
[2024-06-15T14:42:48Z DEBUG triangulate_rs::app] current cursor position:(633,476)
[2024-06-15T14:42:48Z DEBUG triangulate_rs::app] Pushing point coordinate:(633,96)
[2024-06-15T14:42:48Z DEBUG triangulate_rs::app] current cursor position:(633,476)
[2024-06-15T14:42:48Z DEBUG triangulate_rs::app] current cursor position:(633,477)
[2024-06-15T14:42:48Z DEBUG triangulate_rs::app] current cursor position:(633,477)
[2024-06-15T14:42:48Z DEBUG triangulate_rs::app] current cursor position:(634,479)
[2024-06-15T14:42:48Z DEBUG triangulate_rs::app] current cursor position:(720,349)
[2024-06-15T14:42:48Z DEBUG triangulate_rs::app] Pushing point coordinate:(720,223)
[2024-06-15T14:42:48Z DEBUG triangulate_rs::app] current cursor position:(719,348)
[2024-06-15T14:42:48Z DEBUG triangulate_rs::app] current cursor position:(719,348)
[2024-06-15T14:42:48Z DEBUG triangulate_rs::app] current cursor position:(719,348)
[2024-06-15T14:42:48Z DEBUG triangulate_rs::app] current cursor position:(718,346)
[2024-06-15T14:42:48Z DEBUG triangulate_rs::app] current cursor position:(714,342)
[2024-06-15T14:42:49Z DEBUG triangulate_rs::app] current cursor position:(548,150)
[2024-06-15T14:42:49Z DEBUG triangulate_rs::app] Pushing point coordinate:(548,422)
[2024-06-15T14:42:49Z DEBUG triangulate_rs::app] current cursor position:(548,150)
[2024-06-15T14:42:49Z DEBUG triangulate_rs::app] current cursor position:(548,150)
[2024-06-15T14:42:49Z DEBUG triangulate_rs::app] current cursor position:(548,153)
[2024-06-15T14:42:49Z DEBUG triangulate_rs::app] current cursor position:(480,280)
[2024-06-15T14:42:49Z DEBUG triangulate_rs::app] Pushing point coordinate:(480,292)
[2024-06-15T14:42:49Z DEBUG triangulate_rs::app] current cursor position:(247,279)
[2024-06-15T14:42:49Z DEBUG triangulate_rs::app] Pushing point coordinate:(247,293)
[2024-06-15T14:42:49Z DEBUG triangulate_rs::app] current cursor position:(247,279)
[2024-06-15T14:42:49Z DEBUG triangulate_rs::app] current cursor position:(247,279)
[2024-06-15T14:42:49Z DEBUG triangulate_rs::app] current cursor position:(247,279)
[2024-06-15T14:42:51Z DEBUG triangulate_rs::monotone_y_partition] vertex6 is start vertex
[2024-06-15T14:42:51Z DEBUG triangulate_rs::monotone_y_partition] vertex8 is start vertex
[2024-06-15T14:42:51Z DEBUG triangulate_rs::monotone_y_partition] vertex7 is merge vertex
[2024-06-15T14:42:51Z DEBUG triangulate_rs::monotone_y_partition] vertex3 is split vertex
[2024-06-15T14:42:51Z DEBUG triangulate_rs::monotone_y_partition] insert diagnoal between 3 and 7
[2024-06-15T14:42:51Z DEBUG triangulate_rs::monotone_y_partition] vertex5 is regular vertex
[2024-06-15T14:42:51Z DEBUG triangulate_rs::monotone_y_partition] interior is left to vertex5
[2024-06-15T14:42:51Z DEBUG triangulate_rs::monotone_y_partition] vertex1 is split vertex
thread 'main' panicked at src\monotone_y_partition.rs:351:19:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\triangulate_rs.exe` (exit code: 101)

**Comment by ShampooDeng** [comment]
A regular vertex is colinear to a neighbor end vertex seems to cause this bug.

**Comment by ShampooDeng** [comment]
#13
